.Dd Jan 20 2025
.Dt GDLVINTRO 7
.Os
.Sh NAME
.Nm gdlvintro
.Nd introduction to GDLV
.Sh DESCRIPTION
.Sy GDLV
is a alternative to Geometry Dash's level format with the
purpose that the format be slimliar to a programming language
like
.Xr perl 1
for people who want to want to create levels inside a text
editor.
.Pp
Please note that
.Sy GDLV
does not have any refrence implementations yet.
.Sh TABLE OF CONTENTS
This documentation is structured in separate manual pages.
.Pp
Here's a list of man pages of this documentation:
.Ss Introduction
.Bl -tag -width 11n -compact
.It gdlvintro
Introduction to GDLV (this page)
.El
.Ss Refrence manual
.Bl -tag -width 11n -compact
.It gdlvmetadata
Statements for level metadata
.El
.Sh NAMING
.Sy GDLV
is a abbreviation for
.Sy Geometry Dash LeVel scripting language .
You can also call it in other slimliar names if you want to.
.Sh AUTHORS
The GDLV language is created by
.An System32 Aq Mt stvgmpl@gmail.com .
